---

language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-linux-redis
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule docker
  - pip install ansible
  - pip install ansible-lint

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - echo test

script:
  # Run tests.
  - ansible-plybook ansible-linux-redis/tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
