---

language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-linux-redis

install:
  # Install test dependencies.
  - pip install molecule docker
  - pip install ansible
  - pip install ansible-lint

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
