---

- name: "Install | Ensure Redis is installed"
  apt:
    name: "{{ redis_package }}"
    state: present
  when: ansible_os_family|lower == 'debian'

- name: "Install | Update epel-release"
  yum:
    name: epel-release
    state: present
  when: ansible_os_family|lower == 'redhat'

- name: "Install | Get Redis using Yum"
  package:
    name: "{{ redis_package }}"
    state: present
    enablerepo: "{{ redis_enable_repo | default(omit, true) }}"
  when: ansible_os_family|lower == 'redhat'
