---

- name: "Config | Template Redis config file to {{ redis_conf_path }}"
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644

- name: "Config | Verify Redis service ({{ redis_daemon }}) is started and enabled"
  service:
    name: "{{ redis_daemon }}"
    state: started
    enabled: true
