---

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
  - name: instance
    image: "${MOLECULE_DISTRO}"
    privileged: true

provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint

scenario:
  name: default
