---

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}

scenario:
  name: default
