---

name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        which pip
        pip install --upgrade pip
        pip install molecule docker
        pip install ansible
        pip install ansible-lint
    - name: Run molecule
      run: |
        molecule test
      env:
        matrix: |
          - MOLECULE_DISTRO: centos6
          - MOLECULE_DISTRO: centos7
          - MOLECULE_DISTRO: centos8
          - MOLECULE_DISTRO: ubuntu1404
          - MOLECULE_DISTRO: ubuntu1604
          - MOLECULE_DISTRO: ubuntu1804
          - MOLECULE_DISTRO: debian8
          - MOLECULE_DISTRO: debian9
          - MOLECULE_DISTRO: debian10
